### ISSUE TITLE
Knex migration problem

### ISSUE THREAD

**Issue by rosenbluth** [diegogoding/indago#12]
Someone deleted these files but did not fix the migrations table

```
The migration directory is corrupt, the following files are missing: 20161017084503_trips.js, 20161017085348_trip_types.js, 20161017085434_trip_parent_childs.js
    at validateMigrationList (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/knex/lib/migrate/index.js:498:11)
    at PassThroughHandlerContext.finallyHandler (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/samuelrosenbluth/Desktop/galvanize/Q2-project/indago/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by diegogoding** [comment]
the trips is now called plans

**Comment by diegogoding** [comment]
dropdb indago_dev then createdb inidago_dev

**Comment by rosenbluth** [comment]
thank you
